### ISSUE TITLE
Plugin crashes on Android

### ISSUE THREAD

**Issue by mtflud** [Telerik-Verified-Plugins/Mapbox#78]
Hi,
The plugin is crashing for me on Android 6.0 with the following message:
java.lang.IllegalArgumentException: unexpected url: 
at okhttp3.Request$Builder.url(Request.java:142)
at com.mapbox.mapboxsdk.http.HTTPContext$HTTPRequest.<init>(HTTPContext.java:65)
at com.mapbox.mapboxsdk.http.HTTPContext$HTTPRequest.<init>(HTTPContext.java:52)
at com.mapbox.mapboxsdk.http.HTTPContext.createRequest(HTTPContext.java:49)

Any idea what this is about?
Cheers

**Comment by cusspvz** [comment]
Could you please show your code?

**Comment by mtflud** [comment]
Crashlitics reveals this error:

```
Exception java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.blah-2/base.apk"],nativeLibraryDirectories=[/data/app/com.blah-2/lib/arm64, /data/app/com.blah-2/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libmapbox-gl.so"
```
Closing, as it's related to #72
